services:
  - type: web
    name: sealba
    env: python
    plan: free
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app.py --server.port $PORT --server.address 0.0.0.0"
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
